name: Combine files from the patterns folder into a single file and deploy to the GitHub Pages

on: 
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Combine all patterns into a single file
        uses: mikefarah/yq@master
        with:
          cmd: yq '.' patterns/*.yaml > patterns.yaml
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # upload entire directory
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

